In [10]:
import pandas as pd
import numpy as np 
from pycaret.regression import *
import warnings
warnings.filterwarnings("ignore")

In [11]:
# few modifications to https://www.kaggle.com/code/kotrying/tps-2022-03-lgbm
train = pd.read_csv('C:/Users/asane/Desktop/kaggle project/train.csv',index_col='row_id')
test = pd.read_csv('C:/Users/asane/Desktop/kaggle project/test.csv',index_col='row_id')
train['time'] = pd.to_datetime(train.time)
# delete official holiday                                                 
train['offical_holiday'] = train.time.dt.date.astype(str).str.contains('1991-05-27|1991-07-04|1991-09-02').astype('int')
train=train[train['offical_holiday']==0]
train=train.drop('offical_holiday',axis=1)
# train on data for Mondays to Thursdays and complete months only
train=train[(train.time.dt.weekday< 4) & (train.time.dt.month > 4)]

In [12]:
def pre_process(df): 
    df['time'] = pd.to_datetime(df['time'])
    df['month']= df.time.dt.month
    df['day']= df.time.dt.dayofyear
    df['am'] = (df.time.dt.hour < 12) & (df.time.dt.hour >6)
    df['wkday'] = df.time.dt.weekday
    df['time']= (df.time.dt.hour-12)*3+df.time.dt.minute/20
    df['xydirday']= df.x.astype(str)+df.y.astype(str)+df.direction+df.day.astype(str)
    df['xydir'] = df.x.astype(str)+df.y.astype(str)+df.direction
    df['all']= df['xydir']+df.time.astype(str)
pre_process(train)
pre_process(test)
# calculate average traffic flow for each time of day 
mapper_avg = train[['all','congestion']].groupby(['all']).median().to_dict()['congestion']

In [13]:
train['avg']= train['all'].map(mapper_avg)
test['avg']= test['all'].map(mapper_avg)
train= train[train.time >=0]
display(train.head(2),test.head(2))

,time,x,y,direction,congestion,month,day,am,wkday,xydirday,xydir,all,avg
row_id,,,,,,,,,,,,,
142220,0.0,0,0,EB,27,5,121,False,2,00EB121,00EB,00EB0.0,50.0
142221,0.0,0,0,NB,24,5,121,False,2,00NB121,00NB,00NB0.0,35.0

,time,x,y,direction,month,day,am,wkday,xydirday,xydir,all,avg
row_id,,,,,,,,,,,,
848835,0.0,0,0,EB,9,273,False,0,00EB273,00EB,00EB0.0,50.0
848836,0.0,0,0,NB,9,273,False,0,00NB273,00NB,00NB0.0,35.0

In [14]:
# few modifications to https://www.kaggle.com/code/kotrying/tps-2022-03-lgbm
reg = setup(data = train,
            target = 'congestion',
            session_id=999,
            data_split_shuffle = True, 
            create_clusters = False,
            fold_strategy = 'groupkfold',
            fold_groups = 'xydir',
            use_gpu = False,
            silent = True,
            pca = True, 
            pca_components = 10,
            fold=10,
            ignore_features = ['all','day','xydirday'],
            n_jobs = -1)

In [16]:
top3 = compare_models(sort = 'MAE', n_select=3, exclude = ['lar',  'rf', 'et', 'gbr', 'xgboost'])

ValueError: Estimator Not Available xgboost. Please see docstring for list of available estimators.

In [17]:
blender = blend_models(top3)

NameError: name 'top3' is not defined

In [18]:
test['pred'] = (predict_model(final, data=test)['Label']).round()

# Idea from https://www.kaggle.com/code/ambrosm/tpsmar22-generalizing-the-special-values
sep = train[(train.day >= 246) & (train.time >= 0)]
lower = sep.groupby(['time', 'x', 'y', 'direction']).congestion.quantile(0.15).values
upper = sep.groupby(['time', 'x', 'y', 'direction']).congestion.quantile(0.7).values
test.pred = test.pred.clip(lower, upper)
# for roadways with low value count replace prediction with nearest value from the training data
for xydir in set(test.xydir):
    
    xydir_counts = train.loc[train.xydir ==xydir,'congestion'].value_counts()
    
    l = xydir_counts[(xydir_counts > 200)] # experimental
    if len(l) > 2: # experimental
        l = list(l.index)
        test.loc[test.xydir ==xydir,'pred']= test.loc[test.xydir ==xydir,'pred'].map(lambda y: min(l, key=lambda x:abs(x-y)))

NameError: name 'final' is not defined